ledger-report.el
This PR adds a small feature, allowing the user to run another named report while in the report buffer. This way, if you have a series of named reports you run regularly, you can cycle through them in the report buffer instead of going back to the ledger buffer and re-running a report from scratch.
It uses the `ledger-report-redo` machinery for compatibility, so it should set all of the required local variables.
I've used the key `S` for this (a mnemonic for "select"), but I'm open to other suggestions.
=> Add the ability to re-run another named report while in the report buffer

test/complete-test.el, test/context-test.el, test/exec-test.el, test/fontify-test.el, test/mode-test.el, test/navigate-test.el, test/occur-test.el, test/post-test.el, test/reconcile-test.el, test/sort-test.el, test/state-test.el, test/test-helper.el, test/xact-test.el
Header is respecting conventions described in
"Conventional Headers for Emacs Libraries" at
https://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html
=> Add header in test.el files

ledger-post.el
Hi,
Thanks for ledger-mode!
It's all in the commit message, I guess, which is:
Push mark to simplify post-edit action
* ledger-post.el(ledger-post-edit-amount): Added (push-mark) before entering calc. This allows to finalize the post edit from the calc buffer using C-u y.
Best regards,  Marco
=> Simplify the usage of ledger-post-edit-amount

ledger-mode.el
otherwise fill-paragraph in text mode does wrong things if, like me, you
use semicolons a lot in prose.
=> make comment-start buffer-local

ledger-check.el, ledger-context.el, ledger-mode.el, ledger-occur.el, ledger-reconcile.el, ledger-regex.el, ledger-schedule.el, test/test-helper.el
Switching to `cl-lib` has been a to-do for a while. This PR makes the change, and also switches the travis build to evm and cask, which make cross-Emacs testing and package installation easy.
NOTE: I don't expect the travis build for this branch to work immediately, so this PR should be considered a work in progress.
=> Use cl-lib package rather than cl

ledger-mode.el
Need to goto-char start later otherwise target just points to the first line, which isn't where point started (probably)
=> Fix ledger-mode-clean-buffer not navigating back to where it started

ledger-exec.el, ledger-reconcile.el, ledger-xact.el
- Always check exit code, and consider non-zero to be a failure
- Redirect stderr to avoid warnings from polluting captured output (fixes #38)
- Fix ledger-add-transaction, which wrapped ledger execution with its own (broken) error handling
(Filing as pull request to obtain an isolated build: will merge immediately upon build success.)
=> More robustly execute ledger

ledger-regex.el
When `ledger-context-at-point` is applied to:
```
Expenses:Food:Dining                      £50.00  ;foobar
```
We obtain:
```
(acct-transaction account ((indent "   " 8664) (status nil nil) (account "Expenses:Food:Dining" 8668) (separator "                      " 8688) (commoditized-amount "£50.00" 8710) (separator "£" 8710) (comment "50.00" 8711)))
```
Notice that the match values for separator and comment are the sub-matches of commoditized-amount.  This patch creates no-group variants of the amount and commodity regexps so that they can be used in the commoditized amount regexp.  After this patch the match values are correct:
```
(acct-transaction account ((indent "   " 8664) (status nil nil) (account "Expenses:Food:Dining" 8668) (separator "                      " 8688) …
```
=> Fix group matching of `ledger-commoditized-amount-regexp`

ledger-complete.el
This makes the output of ledger-accounts-list-in-buffer and ledger-accounts-tree more readable, which helps when debugging.
=> Drop text properties when gathering account names

ledger-mode.el, ledger-report.el
Forcing completion makes it impossible to use regexps or partial names (at least
with IDO).
=> Don't force completion in ledger-completing-read-with-default

ledger-init.el, ledger-reconcile.el
This becomes a byte compiler warning in Emacs 26
=> All defcustoms should specify :type

ledger-xact.el
This prevents the transaction highlight from interfering with the region
highlight, as for example in the following case:
```
<1>2017-01-01 * Test
Expenses:A  $15
Income:B
2017-01-01 * Test
Expenses:A  $15
Income:B
<0>
```
(Place point on <0>, then press C-SPC and move the point to <1>: note how
the transaction overlay takes precedence over the region overlay, which is undesirable)
=> Only highlight current transaction if region is inactive

.travis.yml, ledger-complete.el, test/Makefile, test/context-test.el, test/fontify-test.el, tools/travis-install-ledger.sh
This required the following changes:
* Dropping the OSX builds: the Travis OSX builders are saturated.
* Reverting to the version of Boost contained in the official Ubuntu repos; that's one version behind the one in the PPA, but that doesn't seem to be a problem.  The PPA wasn't updated to provide trusty builds.
* Disabling warnings-as-errors on Emacs 24.3, since that version of Emacs produces many false positives that get turned into hard errors.
* Fixing ~25 test failures: two in context-tests (a new feature was implemented but the test had not been updated, and string-greater-p was used without providing a shim for Emacs 24.3, which doesn't have that function), and the rest in fontify-tests (most of these were of the following form: the test expected the newline following a string to …
=> Fix Travis builds

ledger-check.el, ledger-commodities.el, ledger-complete.el, ledger-context.el, ledger-exec.el, ledger-fontify.el, ledger-fonts.el, ledger-init.el, ledger-mode.el, ledger-navigate.el, ledger-occur.el, ledger-post.el, ledger-reconcile.el, ledger-regex.el, ledger-report.el, ledger-schedule.el, ledger-sort.el, ledger-state.el, ledger-texi.el, ledger-xact.el
Prefer `lexical-binding t`
This started out as an attempt to fix a few compiler warnings, which I'll submit later. The compiler couldn't find `lexical-let*` as a function so I decided to remove it rather than require cl at compile
=> Lexical bindings

ledger-report.el
setq'ing it means the buffer wasn't read-only before this e.g. after pressing `e` to edit a report
=> let-bind buffer-read-only

ledger-report.el
- let-bind inhibit-read-only so that the report is put back in
read-only-mode
- don't call forward-paragraph if the report is in the header rather
than in the buffer
=> Improve ledger-report-reverse-lines

doc/ledger-mode.texi
Just replacing 'it' with 'its'.
Noticed this while reading the docs and thought I'd submit a quick patch.
=> Fix typo in ledger-mode.texi

ledger-report.el
This PR makes ledger-master-file a buffer-local variable, which is what the documentation of ledger-master-file (the function) says it is.
Also some bonus documentation changes/improvements mostly to satisfy checkdoc.
=> Ledger master buffer local

CMakeLists.txt
This reverts git://github.com/ledger/ledger.git's commit
ba60418991162715a42044b67e594d50ede2de14.
=> Revert "Fix emacs lisp build chain"

.travis.yml
Adds a test that fails if ledger-mode doesn't byte-compile without warnings/errors. 
It looks like the ubuntu-elisp ppa updated to Emacs 26 at some point. I can't figure out how to add back in a test for Emacs 25.
The tests will of course fail right now since #88 hasn't been merged :-)
=> Make travis error on byte compiler warnings

.travis.yml, README.md, ledger-flymake.el, ledger-mode.el
Flymake, Emacs's built-in on-the-fly syntax checker, got a major
overhaul in Emacs 26. This means we can get built-in syntax checking
without requiring users to install both flycheck.el and
flycheck-ledger.el. The checking is done via `ledger balance`. Things
to keep in mind that as of now (the initial implementation):
- It will honor settings from users ~/.ledgerrc files (I'm not sure if
this is a good thing or a bad thing)
- ~It will error if Emacs can't find ledger (i.e. if (executable-find
"ledger") fails)~ Now uses `ledger-binary-path`
- ~There is no way yet to customize calls (using --pedantic, for
example), though this would be easy to implement in the future~ Supports `--pedantic` and `--explicit`
=> Add support for flymake in Emacs 26+

ledger-report.el
This controls whether ledger-report will call
shrink-window-if-larger-than-buffer or not.
=> ledger-report: New option, ledger-report-resize-window

ledger-mode.el, ledger-report.el
The function isn't defined anywhere so these all produce errors. I
re-define the function as an obsolete alias for ledger-report-quit and
replace the keybindings.
=> Remove ledger-report-kill keybindings

ledger-report.el
A command like 'ledger reg' does not include a final space, and thus wouldn't
get links.  This bug was surfaced by e098be20cf603f48dfe18c6237546a8c49e1f97c.
=> Fix a regexp in ledger-report--cmd-needs-links-p

ledger-init.el
Current code assumes that the ledger configuration file will be opened
in a similarly named buffer. This can break. New code removes this
assumption and passes the correct buffer as parameter.
=> Pass buffer instead of filename as BUFFER parameter

ledger-report.el
When running reports, add an option that allows a user to specify whether
--strict is passed to ledger when running reports.
=> Add option that allows --strict to be used for reports

ledger-post.el, ledger-regex.el, test/complete-test.el
- exclude comments from being recognized as accounts
- remove [] and () from account names in virtual postings
Add a unit test to check that all account references and only those are detected.
To do the above, I had to fix ledger-post-align-postings which previously only working because comment lines were considered accounts.
=> Fix account-recognizing regular expressions

ledger-fontify.el, ledger-fonts.el
- Declare two variables used by multiline font-lock
- Require ledger-fontify in ledger-fonts for ledger-fontify-xact-state-overrides
=> Silence the byte compiler

ledger-complete.el
Emacs 27 fixes the typo and obsoletes the old function, so we'll use
defalias to define the typo-free function unless it's already bound.
=> Define pcomplete-uniquify-list if not defined

ledger-report.el
`ledger-report-after-report-hook' is run after creating the
ledger-report buffer, inserting contents, and setting local variables
like `ledger-report-name'.
I find it useful to put a function in there that moves point to the
bottom of the report buffer but make it conditional on
`ledger-report-name'.
=> ledger-report: New hook variable

ledger-report.el
@purcell turns out we need `string-match` because of the call to `replace-match`. So I added it back and wrapped it in `save-match-data`.
=> Fix ledger-report-toggle-default-commodity

ledger-report.el
The main effect of this is that ledger-report buffers are now
read-only all of the time rather than only sometimes. We're also less
likely to turn on modes that don't make sense for report buffers (like
flyspell-mode) that users may have added to text-mode-hook.
=> Make ledger-report-mode derive from special-mode

ledger-flymake.el
The `make-process` commands only accepts a list of strings but when
`ledger-flymake-be-pedantic` and/or `ledger-flymake-be-explicit` is not set to
true it will fail as that list now contains nil. Changed it to just return an
empty string when a setting isn't enabled.
Edit: Fixed quotes in markdown
=> Fixed flymake backend error

ledger-flymake.el
Removing the `nil` entries in the command list instead of setting them to empty
strings. As empty strings might mess with the command.
This cleaner and safer compared to the fix in #155.
=> Cleaner fix for the flymake backend.

doc/ledger-mode.texi
All the other Emacs major modes I have installed have "Emacs" as the dircategory. This makes ledger-mode respect that convention.
=> * doc/ledger-mode.texi: Change dircategory to Emacs

ledger-reconcile.el
Accounts containing virtual transactions will not show the appropriate cleared balance.
This closes #153.
=> Use --real when reconciling accounts

doc/ledger-mode.texi, ledger-xact.el
Hello,
I’ve written a small patch to add the possibility for user to insert a blank line after a transaction inserted with `ledger-copy-transaction-at-point`. The default behaviour only inserted a single `\n` after the transaction, which required manual fixing every time a transaction was to be copied.
I’ve also updated the manual to mention the variable in the relevant node (*Copying Transactions, Editing Amounts, Adding Transactions, The Ledger Buffer*).
I’m not sure if the Elisp is as good as it could be, nor if it flouts any convention I may not know, but I’m not very advanced with the language or with coding in general (although I do hope to improve).
(I’m still very new to the concept of contributing to projects and to opening pull requests, so please excuse me if I’ve done anything …
=>  Add ledger-copy-transaction-insert-blank-line-after

ledger-xact.el
Given that `xact`s have two major pieces of information: payee and date, I figured ledger-mode would benefit from the symmetry of `ledger-xact-date`. To this end, I've factored out code to retrieve the context of an xact surrounding the point: `ledger-xact-context`.
=> Refactor ledger-xact-payee, add ledger-xact-date

ledger-xact.el
Fixes the regression pointed out by @ShuguangSun [in comments to #134](https://github.com/ledger/ledger-mode/pull/134#issuecomment-475467120).
=> ledger-add-transaction: On new transaction, leave point after date

ledger-xact.el
=> ledger-read-transaction: Pre-fill year and month but use full date as default

ledger-exec.el
`ledger-binary-path` should be risky so people can't be tricked into running a malicious executable via a file-local variable setting.
=> Make ledger-binary-path risky

ledger-xact.el, test/reconcile-test.el
Otherwise when we delete a transaction between two transactions, we're
left with a few blank lines instead of just one.
=> Remove blank lines after ledger-delete-current-transaction

ledger-report.el
Erase the report buffer rather than killing it and recreating it. This
allows users to use functions like `display-buffer-reuse-window' to
manager where the ledger-report buffer shows up.
=> Don't kill the report buffer on every new report

ledger-complete.el
Otherwise this makes payee completion difficult.
Closes #181
=> Don't include current line's payee in ledger-payees-in-buffer

doc/ledger-mode.texi, ledger-navigate.el, test/navigate-test.el
These are two commands I use quite often to help me navigate between uncleared transactions. If people think they're useful enough to include in ledger-mode, I'm happy to write up documentation and some tests.
=> New commands ledger-navigate-{next/previous}-uncleared

NEWS.org, ledger-complete.el, test/complete-test.el
New option ledger-accounts-exclude-function if non-nil is a function that can be used to filter accounts that ledger-mode offers for completion. It gets one argument which is a list containing the account name and any subdirectives associated with the account.
I made this because I have quite a few "closed" accounts that I don't want offered by completion:
```
account Assets:Old Checking
assert date<=[2018-01-01]
```
There's also a new function ledger-accounts-in-buffer that returns a list of accounts along with any subdirectives.
=> Add a way to filter account list for completion

ledger-fonts.el
This is a new face attribute in Emacs 27 and without this, the
highlighting stops at the end of the text instead of continuing to the
end of the window.
=> Use :extend in ledger-font-xact-highlight-face in Emacs>=27

ledger-report.el
Fix #226.
An alternative would be to check at the beginning of `ledger-report` to see if the current buffer is a `ledger-report-mode` buffer and not prompt the user to save, but that seems less clean than this approach.
=> Mark report buffer not modified in ledger-report-redo

ledger-xact.el
* ledger-xact.el (ledger-read-transaction): Use ledger-read-date,
which uses org-read-date, which has a nice calendar. Now C-c C-a pops
up with a calendar and has movement with the usual org keybindings. As
a bonus, input like +2w now works too.
----
#
=> Use a calendar for reading dates

ledger-report.el
I missed these in #227.  All locations where `inhibit-read-only` is bound are
now accounted for.
=> Mark report buffers not modified

CMakeLists.txt
Without this, cmake raises an objection:
> CMake Warning (dev) in CMakeLists.txt:
>   No project() command is present.  The top-level CMakeLists.txt file must
>   contain a literal, direct call to the project() command.  Add a line of
>   code such as
>
>     project(ProjectName)
>
>   near the top of the file, but after cmake_minimum_required().
>
>   CMake is pretending there is a "project(Project)" command on the first
>   line.
> This warning is for project developers.  Use -Wno-dev to suppress it.
```
% cmake --version
cmake version 3.16.1
CMake suite maintained and supported by Kitware (kitware.com/cmake).
```
=> Set project(ledger-mode) to shut cmake up.

ledger-navigate.el
Candidate fix for first part of <https://github.com/ledger/ledger-mode/issues/71>.
=> Stop at end of last line, not at first character of next line.

.github/workflows/test.yml, NEWS.org, ledger-complete.el, ledger-mode.el, test/Makefile, test/complete-test.el, test/fontify-test.el, test/test-helper.el
Fix for #237. 
Requires `completion-table-with-cache` which requires Emacs 24.4 (we currently support back to 24.3). I took the opportunity to bump our minimum version up to 25. 25 was released ~4 years ago and AFAIK all the major distros have updated to at least 25.
=> Use a cache for account completion

ledger-init.el
input-date-format is the format used for the ledger, date-format is
the format used for reports. ledger-format-date is used for e.g.
ledger-add-transaction so it should use input-date-format.
Closes #245
=> Use input-date-format in ledger-format-date

ledger-report.el
ledger-report-quit's current behavior is to reset the window
configuration to whatever the window configuration was when the report
was originally called. This can be jarring when the report buffer was
generated, then the user went off doing other things (changing the
window configuration), then quits the report window.
The new behavior simply quits (and kills) the report buffer using
quit-windows-on, which works well with the display-buffer framework.
=> Make ledger-report-quit less opinionated about windows

ledger-report.el
Fix #275.  Update the regular expression for absolute paths in the ledger report to allow Windows-style absolute paths (`C:\...`) in addition to Unix-style ones (`/...`).
=> Recognize Windows-style absolute paths in links

ledger-report.el
This removes one blocking point when displaying reports with `ledger-binary-path` pointing to hledger.
=> Add ledger-report-native-highlighting-arguments

NEWS.org, doc/ledger-mode.texi, ledger-xact.el
ledger-add-transaction now uses org-read-date for its nice
functionality and prompts users for additional text a second time in
the minibuffer. ledger-add-transaction-prompt-for-text can be set to
disable the additional prompt.
Closes #252
The downside is the user is now prompted twice whereas before it was just the one time. `org-read-date` doesn't seem to return any usable info about misc text it receives so we can't grab it somehow.
=> Allow ledger-add-transaction to parse more text

ledger-init.el
This fixes the following customization:
(custom-set-variables
'(ledger-default-date-format ledger-iso-date-format))
Otherwise, when `ledger-init` is loaded, Custom attempts to evaluate
`ledger-iso-date-format` immediately after `ledger-default-date-format` is
defined but before `ledger-iso-date-format` is defined, which leads to an
unbound variable error.
=> Define ledger-iso-date-format before ledger-default-date-format

.github/workflows/test.yml, test/Makefile
For some reason, existing CI was running checkdoc against the .el files under "test", which isn't very helpful.
=> Run checkdoc on the main elisp files, not the test files

ledger-context.el, test/context-test.el
Fix #302 by "moving" the newline from the payee regex to the comment regex.
=> Fix payee including trailing newline

ledger-init.el
When ledger-init-file-name is set to nil, this function fails with a type error
in `file-name-nondirectory`.
This PR changes load-init-file to only attempt any sort of loading if `ledger-init-file-name` is non-nil.
=> ledger-init: Fix type error in ledger-init-load-init-file

ledger-exec.el
This fixes the xact-test test suite for me, which was broken because my
~/.ledgerrc specifies the ISO date format, whereas the test expects the default
`%Y/%m/%d` format.
I think this is one place where "use ledger-default-date-format consistently when inserting new transactions" was violated.
=> ledger-exec: Pass in ledger-default-date-format

test/fontify-test.el, test/navigate-test.el, test/test-helper.el
This prevents individual user settings from affecting test results.
This PR depends on #304 and otherwise doesn't pass tests.
=> Do not load user's ledger init file in tests

ledger-exec.el, ledger-regex.el, ledger-xact.el, test/regex-test.el, test/xact-test.el
This pull request fixes #307.  This branch itself includes some commits from #305 and #267, but I didn't know how to express the dependency in GitHub Pull Request terms.  In any case, those should probably be reviewed first (#267 is a refactor and also includes some bugfixes).
=> Fix #307: ledger-add-transaction inserts in the wrong place when xacts have effective dates 

ledger-exec.el, ledger-regex.el, test/regex-test.el
I noticed that several of the capture group functions like `ledger-regex-full-date-effective` didn't work as advertised, and upon further inspection found several bugs in the `ledger-define-regexp` macro.
This pull request fixes those bugs, namely:
1. Incorrect assumptions about the number of capture groups in small regexps (which don't contain sub-groups)
2. Re-use of capture group index when a sub-group appears twice (viz., two `iso-date`s in `full-date` were given the same index)
0f67184 defines some tests which demonstrate the capture group counts and indices as generated by `ledger-define-regexp`.  Each commit that changes behavior updates the test to reflect the new behavior, so the tests serve as an indication of the current state.
In order to ensure that changing these indices and …
=> Fix capture-group counts and indices in ledger-regex.el

ledger-reconcile.el
Fix #311 by calling ledger-occur in the main ledger buffer.  Also, we may as well regexp-quote the account name, since it may contain regexp metacharacters.
=> Fix ledger-narrow-on-reconcile

ledger-fonts.el
This makes exports fail when Ledger snippets are embedded in an Org file.
=> Replace reference to non-existing face variable

.github/workflows/test.yml
Hoping to address build failures in PRs, which might also be caused by incompatiblities in the nix file in the ledger repo itself.
=> Update Actions versions

ledger-reconcile.el
Thanks for merging #332, @purcell!  Just a quick follow-up because I forgot to wrap the funcall in a `save-excursion`.  I didn't judge `save-match-data` to be necessary here but I may well have missed something.
=> Call ledger-reconcile-insert-effective-date in save-excursion

ledger-reconcile.el
After entering an erroneous target amount, and then correcting it with `ledger-reconcile-change-target`, I wanted to see that the difference from target was now 0, but unfortunately the balance wasn't displayed.
This PR makes `ledger-reconcile-change-target` display the balance after setting the target.
=> ledger-reconcile-change-target: Display balance after changing

ledger-xact.el
This PR ensures that no empty lines are added to the end of the buffer when `ledger-copy-transaction-insert-blank-line-after` is `t`.
=> Do not add a blank line at the end of the buffer

ledger-post.el
Traditionally indentation related customizations are considered safe as file local variables.
=> Declare ledger-post-account-alignment* variables safe

ledger-regex.el, test/reconcile-test.el
Prior to this change, ledger-read-commodity-string returned strange things like `'(53 "0.")` for an input of `0.53` (with a default commodity of USD, it should have returned `'(53 "USD")`).
I decided to preserve a current property of the regexes, which is that leading zeros are still disallowed on non-zero numbers.
=> ledger-split-commodity-string: Recognize amounts less than 1

ledger-regex.el
Right now postings with = and + prefixes in amount (i.e. `= 100 EUR` are not indented when pressing tab, this PR fixes that and adds ability to put spaces after these prefixes.
Indent function was changed because when we allow whitespace before prefix current indent function will just align amount including prefix meaning things like `=           100 EUR` will be left as is. I think it is better to trim this whitespace. If this breaks some expected workflow then I can make this part toggleable via config or remove it and keep it a part of my personal config.
I only tested this by checking that indent works properly and I don't know if this could affect other places
=> Add support for + and = prefixes in amount and ability to add whitespace after them

ledger-flymake.el
Currently, multiple file setup ends up with incorrent linting due to `ledger-flymake` only considering the current file. In multiple file setup, where you would have your account definition separate from the actual accounting, this would lead to Flymake incorrectly linting accounts, commodities, etc as missing, when they're not. This simple change simply checks if the `(ledger-master-file)` is a file or not, and if so use it, otherwise default to using the current file.
We could make it so that the `(file-exists-p ...)` check is removed, but I don't know what is the desired behaviour in this case. Should we just assume that the user is providing the correct master file?
You could test out this feature by using the following files:
`foo.ledger`
```ledger
2023-01-01 Foo Bar
Foo …
```
=> Use ledger-master-file for Flymake when available

ledger-mode.el
I find narrowing to a single transaction useful sometimes, this change makes it so that `narrow-to-defun` (bound to `C-x n d` by default) will do just that.
=> Make `narrow-to-defun` work on ledger transactions/directives

ledger-reconcile.el
The variable `ledger-reconcile-clear-whole-transactions` does not exist. The variable `ledger-clear-whole-transactions` is what it's actually referring to.
Ran into this while I was configuring my ledger-reconcile setup for the first time, and thought I could fix this :+1:
=> Minor documentation update

ledger-regex.el, test/fontify-test.el, test/reconcile-test.el, test/test-helper.el
I changed the regex for fontifying postings so that inline comments are only fontified when they meet the ledger specification (according to [manual section 4.7.1](https://ledger-cli.org/doc/ledger3.html#Transactions-and-Comments:~:text=ACCOUNT%20%20AMOUNT%20%20%5B%3B%20NOTE%5D)).
This change has no functional impact on ledger-mode's operation, but it will help users learn proper ledger file format, ensuring that they don't run into issues with `ledger` or `ledger-mode`. If users don't put a "long space" in front of posting comments, `C-c C-b <ledger-post-edit-amount>` destroys all (or part) or the comment and places point in the wrong location.
**Rationale:**
Comments that are on the same line as a posting are supposed to have a "long space" in front of them (one tab or 2+ whitespace …
=> Changed comment highlighting to match the ledger file specification

.dir-locals.el
Starting in Emacs 28.1, bug-reference emits a warning if bug-reference-bug-regexp's first capture group does not contain its other capture groups (2-10).  The first capture group is used to specify which part of the buffer should be fontified as a link, and so it should include the bug number (capture group 2).
=> Fix bug-reference-bug-regexp to conform to its contract

ledger-complete.el, test/complete-test.el
Account subdirectives (like assert and note) might match the account name regex but should not be included in the list.  Instead of scanning each line in the buffer for such occurrences, only scan occurrences in transactions.
Fixes #380.
=> ledger-accounts-in-buffer: Don't include account subdirectives

doc/ledger-mode.texi, ledger-reconcile.el, test/reconcile-test.el
Also replace "recon" in docstrings and variable names with "reconcile".
=> Rename ledger-recon-buffer-name to be consistent

ledger-post.el, ledger-regex.el
I originally just wanted to add a small docstring tweak and suppress the "Mark
set" message from this command, but this PR also includes some drive-by
refactors.
Also, add a hint to the Calc welcome message suggesting the user to press C-u y,
which will insert the top stack value into the ledger buffer and close calc.
=> Rework ledger-post-edit-amount

ledger-mode.el
* ledger-mode.el (ledger-mode-clean-buffer): Improve to make it
remember the point within the transaction. Before, the point was
always moved at the beginning of the current transaction, making the
function inconvenient for use within `before-save-hook'.
=> Make ledger-mode-clean-buffer remember point within transaction

ledger-post.el
Unfortunately, a4115ddfed6440897c18137ded5b6b2d14491c44 had a bad side effect
where, because the calc welcome message was multiple lines, calc-window-height
could be calculated incorrectly, and would be decreased each time calc was
called, eventually leading to it possibly having a negative value.
Instead of displaying a hint message, just put a message in the docstring of
`ledger-post-edit-amount`, which is not quite as nice but won't cause this bug.
=> Fix calc-window-height decreasing each time ledger-post-edit-amount is called

ledger-report.el
By using the `window-max-chars-per-line` instead of `window-width`, which seems exactly what we want here according to the doc:
Return the number of characters that can be displayed on one line.
This function automatically take care of the glyph column.
=> Fix ledger auto report width

ledger-reconcile.el, test/input/demo.ledger, test/reconcile-test.el, test/test-helper.el
Refresh ledger-occur overlays after ledger-reconcile-add
Fix #383.
This PR also includes a couple of drive-by refactors.
=> Refresh ledger-occur overlays after adding a new transaction while reconciling

ledger-check.el, ledger-reconcile.el, ledger-report.el, test/reconcile-test.el
This PR cleans up some use of buffer-local variables in ledger checks, reports,
and reconcile buffers.  These variables are now properly namespaced and
designated as permanent buffer-locals, so they can be set straightforwardly with
setq.
I added docstrings only for the ledger-reconcile buffer-locals, because at least
one of them is used in a test.
While I consider this code mostly pretty straightforward, it does have the
potential to break somebody's personal config if they are referring to any of
these variables by the (un-namespaced) original name.  @purcell, thoughts?
=> Refactor definitions and use of buffer-local variables

ledger-reconcile.el
This commit adds a new customization,
`ledger-reconcile-display-balance-in-header`.  If non-nil, this causes the
reconcile buffer's header line to display the cleared+pending balance, as well
as the difference from target (if any), continuously while reconciling.  I have
found this far more convenient than searching through `*Messages*` for the last
balance message (although I learned that `ledger-display-balance` has a key
binding while implementing this, I still think this feature may be useful).
=> reconcile: Optionally display balance in header line

ledger-occur.el, test/occur-test.el
Fix #54.
This PR adds some regression tests for ledger-occur, as well as refactoring the
overlay creation loop to be a bit easier to understand.
Another option I considered was to use a single overlay for the whole buffer to
make most of it invisible, and then only create overlays to make the match areas
visible.  However, with ledger-occur-xact-face, it highlights the newlines in
between the xacts, which is a little weird, so I didn't end up making this
change.
=> Fix #54 and refactor ledger-occur overlay logic

ledger-complete.el
This is a minor fix to a previous change from @bcc32 — would you mind checking it over please?
The previous loop searched for directives, and the intention of this second loop is to search only for account names used in transactions, so we don't need to use the combined regexp here after all.
=> Use correct regexp when scanning for account names

ledger-sort.el
E.g. sort 2022/5/7 as expected.  Previously one had to write 2022/05/07 to do  the sorting reliably.  Note the zeros!
The price for the fix of the sorting is the work to parse the date for each record.
=> Sort dates without leading 0 naturally

ledger-commodities.el, test/reconcile-test.el
This PR changes `ledger-{add,subtract}-commodity` to allow the second argument's
commodity string not to match the first argument's, as long as the second amount
is zero.  Since subtracting a zero amount is a no-op anyway, this should be fine
in terms of correctness, and alleviates some spurious errors.
Fix #416
=> Fix #416 by allowing subtraction of zero-amount mismatched commodities

test/test-helper.el
I'm not sure why this fix would be necessary, but it seems to make the CI happy.
(I would think `ledger-fontify-extend-region` should be sufficient to make
fontification work reliably, but it's possible Emacs 25.1 is doing something
differently).
=> Attempt to fix flaky ledger-fontify/test-017 on Emacs 25.1

ledger-commodities.el, ledger-post.el, test/post-test.el
If the changes in this PR are desired, I will write unit tests.
=> ledger-xact: Add ledger-xact-fill to insert missing amount

NEWS.org, ledger-context.el, ledger-mode.el, test/mode-test.el, test/test-helper.el
No explicit configuration needed. Currently supports two date formats `2020/12/28` and `2020-12-28`.
=> Use Shift-<up/down> to change dates like in org mode

.github/workflows/test.yml, test/Makefile, test/mode-test.el, test/test-helper.el
This PR makes it possible to run `ledger-mode/test-001` (the only test tagged
`interactive`) in batch mode, and thus lets all tests be run in a uniform way.
This change was prompted by an attempt to switch to using makem.sh for testing
and linting purposes.
=> Remove distinction between interactive and batch tests

ledger-complete.el, test/complete-test.el
ledger-complete-at-point currently seems completely broken for date completion
(e.g., "19" completes to the 19th of the current month, or the previous month,
whichever date is in the past from today).
I added some regression tests that demonstrate the bugs, and then separate
commits to fix each bug.  I plan to squash the test and fix commits together
when merging.
(@purcell, I spent some time fighting with the CI over some old calling
conventions for functions (func-arity, which didn't exist; and encode-time,
which doesn't support a single argument in Emacs < 27, but the multiple-argument
form is marked "obsolete" in Emacs 29).  What's ledger-mode's policy on
supporting Emacs major versions, is there generally some guideline we follow as
to when we're okay with abandoning support for …
=> Fix some bugs in ledger-complete-at-point date completion

NEWS.org, ledger-fonts.el
The :invisible property is not one supported by defface, and in fact this face is never actually used.
Noticed this via a byte compilation warning in the CI for #438
=> Remove unused ledger-occur-narrowed-face

ledger-regex.el, test/context-test.el
This includes prefixed `-` characters when matching commoditized amounts.
Fixes #211
=> Handle prefixed negation on commoditized amounts

ledger-complete.el, test/complete-test.el
This resolves an old FIXME about a wasteful calculation, anyway, but the
motivation is to:
Fix #443
=> Refactor step-by-step completion to avoid checking context bounds twice
