ledger/ledger-mode

ledger-context.el
=> Fix context info retrieval of a transaction header

LICENSE.md
Obtained via:
curl https://www.gnu.org/licenses/old-licenses/gpl-2.0.md -o LICENSE.md
[ci skip]
=> Add license file (GPLv2)

ledger-report.el
At present `ledger-report-do` will insert the report name, command, and a separator line of `===` characters into the buffer as a preface to the output of the report command itself. This seems like functionality that belongs in Emacs's `header-line-format` facility instead.
This PR adds a demo header line containing the report name, buffer, and command as a replacement for the current preface approach.
Sample output before:
After:
The current content and faces of the header are somewhat arbitrary, and I'm open to suggestions as to how to improve them.
=> Makes ledger-report-mode use the header-line for its preface

CMakeLists.txt, ledger-check.el, ledger-exec.el, ledger-init.el, ledger-mode.el, ledger-report.el
1x Build error fix
3x Build Warning fixes
1x documentation for ledger-environment-alist variable
1x wide-spread use of (ledger-master-file)
=> Use ledger master file where applicable

ledger-commodities.el
With these two patches, I have reconciliation working with decimal comma.
=> Fix ledger string to number

ledger-complete.el
David Glasser asked on the mailing list for a faster way to enter transaction dates, to which I suggested this idea:
> I think I might like Tab to autocomplete and canonicalize dates. The
idea is that if you typed a single number at the beginning of line and
pressed Tab, it would expand to the date in the current or last month;
two numbers with a separator would expand to the date in the current
or last year; and separators would be normalized according to
`ledger-default-date-format`. (The “current or last” in both cases would
resolve to yield a date that is not in the future.)
>
> Example: On 2018-01-03, you enter `30` at the start of line, press
Tab, and it expands to `2017-12-30`.
This patch is my attempt to implement that.
=> Implement date completion

ledger-mode.el
Hi,
This patch will add completion when prompted for an account in the minibuffer (for example with `ledger-reconcile').
Thanks,
* (ledger-accounts-in-buffer): New function.
* (ledger-read-account-with-prompt): Use
`ledger-completing-read-with-default'.
* (ledger-get-minibuffer-prompt): New function.
* (ledger-completing-read-with-default): New function.
* (ledger-read-string-with-default): Use
`ledger-get-minibuffer-prompt'.
=> Implement accounts completion

ledger-complete.el
This didn't make it into the previous PR in time :)
=> Don't shim string-greaterp

doc/ledger-mode.texi, ledger-fonts.el, ledger-report.el
* Add a button face and enable clicking on register report lines
* Use ledger's own highlighting in report buffers
Supersedes GH-68? CC @jabranham
=> Improve highlighting in reports

ledger-report.el
CC @jabranham.
The crucial bit is using ansi-color-apply instead of ansi-color-apply-on-region
=> Fix GH-83 by applying highlights as text properties, not overlays

ledger-reconcile.el
Fixes #58. See that issue for further detail.
=> Reconcile: Be aware of ellided default account postings

ledger-report.el
Bound to "$" in ledger-report-mode-map
=> ledger-report-toggle-default-commodity: New command

doc/ledger-mode.texi
=> typos and grammar

doc/ledger-mode.texi
changed "two way" to "two ways" [ci skip]
=> fixed typo in ledger.texi

ledger-xact.el
=> ledger-add-transaction: Do not add blank line at end of buffer

ledger-report.el
* ledger-report.el (ledger-master-file): Move up to silence compiler warning.
(ledger-report-mode-map): Bind C-c C-o C-r to ledger-report.
(ledger-report): Set ledger-master-file in ledger-report.
=> Make ledger-report work in ledger-report-mode buffers

doc/ledger-mode.texi, ledger-complete.el, ledger-mode.el, ledger-post.el, test/complete-test.el, test/mode-test.el
Explanation in git commit messages (mainly the first one). Please play around and let me know what's broken.
Issue #171
CC'ing people participating there: @DamienCassou @enderw88 @basil-conto @glasser
=> Move from pcomplete to completion-at-point-functions

doc/ledger-mode.texi, ledger-complete.el
=> Minor fixups

doc/ledger-mode.texi
=> Remove reference to removed functions

doc/ledger-mode.texi, ledger-init.el
=> Make ledger-default-date-format a user option

ledger-complete.el, ledger-regex.el, test/complete-test.el
=> Match account names more liberally for the sake of completion

ledger-report.el
Ledger report buffers can take a long time to construct because *for (basically) every line in the report buffer* we: 1) call find-file (which switches buffers, taking time), 2) navigate through the file and, 3) add a marker. For me, some reports for accounts with many transactions (more than, say, 1k) can take 5 or 7 seconds to open (on my old, cheap laptop). This is especially annoying because it is redone (and blocks Emacs) every time the ledger buffer is saved.
Instead of doing that, I propose just adding the file & line info to the text properties in the report buffer. I don't think adding a marker gets us anything since we already have ledger-report-redo on after-save-hook so the line/marker info gets recalculated anyway. Doing it this way takes less than a second for those same …
=> Speed up adding ledger report links

NEWS.org, ledger-flymake.el, ledger-init.el, ledger-post.el, ledger-report.el
Cobbled together by glancing through the commits since the v3.1.1 tag. Very possible I missed something.
Hopefully we can tag a new release shortly after this gets merged (#194) 
@purcell
=> Add a news file

ledger-complete.el
Before if we were completing an xact but there was a non-account
line (e.g. a comment), we'd delete the payee and fail to complete the
transaction. Now we use ledger-navigate-end-of-xact to just grab all
the text until the end of the xact, comments and all.
Closes #151
=> Fix ledger-fully-complete-xact deleting payees

.github/workflows/test.yml, README.md
Here's how a basic github actions setup might work. I don't think the feature is available yet for this organisation, though, so I'll file this as a PR for later reference.
=> Try github actions

ledger-complete.el
Use a hash table to avoid gathering duplicate account names, rather
than cl-pushnew which runs in O(n) time for each account.
=> Avoid quadratic-time completion algorithm.

doc/ledger-mode.texi
Update to match the current four variables' names and help.
=> update docs for the Ledger Post customization group

ledger-complete.el
=> Fix step-wise completion of accounts with spaces in the name

ledger-regex.el
=> Remove unnecessary macroexpand calls in ledger-regex

ledger-reconcile.el
Allow the user to customize ledger-reconcile-insert-effective-date by making it
a function that is called with the point at the posting to be cleared.  This
allows the function to decide whether to insert an effective date based on,
e.g., the payee or the account in question.
This is kept backwards-compatible with existing boolean values, which just
behave as a constant-returning function.
=> Allow ledger-reconcile-insert-effective-date to be a function

ledger-complete.el, ledger-context.el, ledger-exec.el, ledger-mode.el, ledger-navigate.el, ledger-occur.el, ledger-post.el, ledger-reconcile.el, ledger-report.el, ledger-schedule.el, ledger-sort.el, ledger-xact.el
=> Shorten docstrings

ledger-fonts.el, ledger-regex.el, test/fontify-test.el
=> Fix amount highlighting when tab is a separator

ledger-complete.el, test/complete-test.el
=> Fix account completion with tab separated amount

ledger-init.el
The main motivation was to prevent the file named in `ledger-init-file-name`
from being "visited" and thus added to my recentf list.  While I was at it,
cleaned up some other things in ledger-init.
=> Miscellaneous refactors to ledger-init.el

ledger-complete.el, ledger-regex.el, test/complete-test.el
=> Add ledger-payees-file for completion, and support payee directives

ledger-init.el, ledger-reconcile.el, test/reconcile-test.el
=> Fix ledger-reconcile-default-date-format not being used
